FROM node:20-alpine3.22

WORKDIR /usr/src/app

COPY package*.json tsconfig.json ./

RUN npm install
RUN npm install -g nodemon ts-node knex

RUN apk add --no-cache postgresql-client bash

COPY wait-for-it.sh start.sh ./
RUN chmod +x wait-for-it.sh start.sh

COPY . .

EXPOSE 8080

CMD ["./start.sh"]
