# 1. Stage para dependências
FROM node:20-alpine AS deps
WORKDIR /app

COPY package*.json ./
RUN npm install

# 2. Imagem final (dev)
FROM node:20-alpine
WORKDIR /app

# libs extras 
RUN apk add --no-cache bash postgresql-client


COPY --from=deps /app/node_modules ./node_modules

# copia resto do projeto
COPY . .

# deixa scripts executáveis
RUN chmod +x start.sh wait-for-it.sh

EXPOSE 8080

# ENTRYPOINT roda só uma vez, ANTES do CMD
ENTRYPOINT ["./start.sh"]

# este comando roda DEPOIS do entrypoint
CMD ["npm", "run", "dev"]
