export enum ParkingErrorCode {
  PARKING_CREATE_FAILED = "PARKING_CREATE_FAILED",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  PARKING_NOT_FOUND = "PARKING_NOT_FOUND",
  PARKING_FETCH_FAILED = "USER_FETCH_FAILED,"
}
